CREATE SEQUENCE s_uzytkownicy
MINVALUE   1000
MAXVALUE   9999
START WITH 1000;

CREATE SEQUENCE s_hasla
MINVALUE 1
MAXVALUE 9999
START WITH 1;

CREATE SEQUENCE s_logi_uzytk
MINVALUE   1
MAXVALUE   10000
START WITH 1;

CREATE SEQUENCE s_kat_menu
MINVALUE   1
MAXVALUE   10
START WITH 1;

CREATE SEQUENCE s_poz_menu
MINVALUE   1
MAXVALUE   80
START WITH 1;